"""Add a phone_number in User Models

Revision ID: 15406a742cf9
Revises: 3ae8a9a8982d
Create Date: 2025-06-11 12:56:11.135444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15406a742cf9'
down_revision = '3ae8a9a8982d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
