"""Add is_read column to Message model

Revision ID: 3ae8a9a8982d
Revises: e46a5254e81a
Create Date: 2025-06-11 11:49:29.948402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ae8a9a8982d'
down_revision = 'e46a5254e81a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_read', sa.Boolean(), nullable=True))
        batch_op.alter_column('recipient_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('recipient_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('is_read')

    # ### end Alembic commands ###
