"""Set ondelete SET NULL for cart_item.product_id

Revision ID: 855d56d34661
Revises: d9a6e60b2a11
Create Date: 2025-07-10 23:47:26.012526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '855d56d34661'
down_revision = 'd9a6e60b2a11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('cart_item_product_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'product_listing', ['product_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('cart_item_product_id_fkey', 'product_listing', ['product_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
