"""Add ON DELETE CASCADE to CartItem.product_id

Revision ID: d9a6e60b2a11
Revises: 8605d99ec7fe
Create Date: 2025-07-10 20:21:02.036813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9a6e60b2a11'
down_revision = '8605d99ec7fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.drop_constraint('cart_item_product_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'product_listing', ['product_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('cart_item_product_id_fkey', 'product_listing', ['product_id'], ['id'])

    # ### end Alembic commands ###
